name: Compile Jekyll site
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7 
        bundler-cache: true 
    - run: bundle install
    - name: Compile code
      run: bundle exec jekyll build