name: Run devices consistency checks
on:
  push:   
    paths:
      - '_devices/**'
  pull_request:   
    paths:
      - '_devices/**'      
      
jobs:
  validate-devices:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        validate-command:
          - checkUnderscoreCount
          - checkEachDeviceHasImage
          - checkNameIsLowercase

    steps:
      - uses: actions/checkout@v2
      - name: Validate
        run: |
          cd ci_dc/
          source util.sh
          ${{ matrix.validate-command }}